[package]
name = "hello"
version = "0.1.0"
authors = ["chris"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paris = {version = "1.4.0", features = ["macros"]}
rand = "0.7"
